/**
 * Canonical step and field order for the Surrogate Application form (Become a Surrogate).
 * Used so that the Available Surrogate detail modal shows the same content and order.
 * Order matches SurrogateApplicationScreen renderStep1() through renderStep8().
 */

export const SURROGATE_APPLICATION_STEPS = [
  {
    step: 1,
    title: 'Personal Information',
    fields: [
      'firstName',
      'middleName',
      'lastName',
      'fullName',
      'dateOfBirthMonth',
      'dateOfBirthDay',
      'dateOfBirthYear',
      'dateOfBirth',
      'age',
      'hearAboutUs',
      'previousSurrogacy',
      'previousSurrogacyCount',
      'bloodType',
      'height',
      'weight',
      'significantWeightChange',
      'race',
      'religiousBackground',
      'practicingReligion',
      'usCitizen',
      'citizenshipStatus',
      'isSingle',
      'isMarried',
      'isWidowed',
      'maritalStatus',
      'spouseName',
      'spouseDateOfBirth',
      'marriageDate',
      'maritalProblems',
      'legallySeparated',
      'separationDetails',
      'divorced',
      'divorceDate',
      'divorceCause',
      'remarried',
      'remarriedDate',
      'widowedDate',
      'lifePartner',
      'partnerName',
      'partnerDateOfBirth',
      'engaged',
      'engagementDate',
      'weddingDate',
      'wantMoreChildren',
      'legalProblems',
      'jailTime',
      'nearestAirport',
      'airportDistance',
      'pets',
      'livingSituation',
      'ownCar',
      'driverLicense',
      'carInsured',
      'transportationMethod',
      'siblingsCount',
      'motherSiblingsCount',
      'location',
      'phoneNumber',
      'email',
      'address',
    ],
  },
  {
    step: 2,
    title: 'Pregnancy & Delivery History',
    fields: ['totalDeliveries', 'deliveries', 'previousSurrogacy', 'previousSurrogacyCount'],
  },
  {
    step: 3,
    title: 'Health Information',
    fields: [
      'healthInsurance',
      'maternityCoverage',
      'insuranceDetails',
      'stateAgencyInsurance',
      'stateAgencyName',
      'insurancePaymentMethod',
      'deliveryHospital',
      'deliveredAtHospitalBefore',
      'abnormalPapSmear',
      'monthlyCycles',
      'cycleDays',
      'periodDays',
      'lastMenstrualPeriod',
      'infertilityDoctor',
      'infertilityDetails',
      'smokingStatus',
      'smokedDuringPregnancy',
      'householdSmoking',
      'householdSmokingDetails',
      'householdMarijuana',
      'alcoholUsage',
      'alcoholFrequency',
      'illegalDrugs',
      'partnerIllegalDrugs',
      'childrenList',
      'pregnancyProblems',
      'pregnancyProblemsDetails',
      'childrenHealthProblems',
      'childrenHealthDetails',
      'breastfeeding',
      'breastfeedingStopDate',
      'surgeries',
      'surgeryDetails',
      'seriousIllnesses',
      'hospitalizations',
      'currentMedications',
      'tattoosPiercings',
      'tattoosPiercingsDate',
      'mentalHealthTreatment',
      'mentalHealthDetails',
      'postpartumDepression',
      'postpartumDepressionDetails',
      'depressionMedication',
      'depressionMedicationDetails',
      'drugAlcoholAbuse',
      'excessHeat',
      'alcoholLimitAdvised',
      'hepatitisBVaccinated',
      'allergies',
      'allergiesDetails',
    ],
  },
  {
    step: 4,
    title: 'Sexual History',
    fields: [
      'pastContraceptives',
      'currentBirthControl',
      'birthControlMethod',
      'birthControlDuration',
      'sexualPartner',
      'multiplePartners',
      'partnersLastThreeYears',
      'highRiskHIVContact',
      'hivRisk',
      'bloodTransfusion',
      'stdHistory',
      'stdDetails',
    ],
  },
  {
    step: 5,
    title: 'Employment Information',
    fields: [
      'currentEmployment',
      'monthlyIncome',
      'spouseEmployment',
      'spouseMonthlyIncome',
      'personsSupported',
      'publicAssistance',
      'householdMembers',
    ],
  },
  {
    step: 6,
    title: 'Education History',
    fields: ['educationLevel', 'tradeSchoolDetails'],
  },
  {
    step: 7,
    title: 'General Questions & Preferences',
    fields: [
      'surrogacyUnderstanding',
      'selfIntroduction',
      'mainConcerns',
      'parentQualities',
      'religiousPreference',
      'unmarriedCouple',
      'heterosexualCouple',
      'eggDonor',
      'spermDonor',
      'olderCouple',
      'coupleWithChildren',
      'sameSexCouple',
      'singleMale',
      'singleFemale',
      'internationalCouple',
      'nonEnglishSpeaking',
      'carryTwins',
      'reductionWilling',
      'amniocentesis',
      'abortionWilling',
      'concernsPlacingBaby',
      'parentsInDeliveryRoom',
      'parentsAtAppointments',
      'notifyHospital',
      'parentsOnBirthCertificate',
      'applyingElsewhere',
      'rejectedElsewhere',
      'attendCheckups',
      'receiveInjections',
      'medicalExaminations',
      'avoidLongTravel',
      'followGuidelines',
      'avoidHighRiskWork',
      'placedChildAdoption',
      'contactDuringProcess',
      'contactAfterBirth',
      'expectedSupport',
      'unsupportivePeople',
      'partnerFeelings',
      'childcareSupport',
    ],
  },
  {
    step: 8,
    title: 'Authorization for Release of Information',
    fields: ['authorizationAgreed', 'firstName', 'lastName', 'email'],
  },
];
